# Generated by Django 4.2.7 on 2025-08-23 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="link_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Истечение токена"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="pending_link_token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Токен привязки"
            ),
        ),
        migrations.CreateModel(
            name="LinkToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(max_length=100, unique=True, verbose_name="Токен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Истекает")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="Использован"),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Telegram ID"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Токен привязки",
                "verbose_name_plural": "Токены привязки",
            },
        ),
    ]
