# Generated by Django 4.2.7 on 2025-08-23 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0002_telegramuser_link_expires_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linktoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Токен привязки",
                "verbose_name_plural": "Токены привязки",
            },
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="link_expires",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="pending_link_token",
        ),
    ]
