# Generated by Django 4.2.7 on 2025-08-23 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=200, verbose_name="Слово")),
                (
                    "translation",
                    models.CharField(max_length=200, verbose_name="Перевод"),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True, null=True, verbose_name="Пример использования"
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Начальный"),
                            ("intermediate", "Средний"),
                            ("advanced", "Продвинутый"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Уровень сложности",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cards",
                    models.IntegerField(default=0, verbose_name="Всего карточек"),
                ),
                (
                    "learned_cards",
                    models.IntegerField(default=0, verbose_name="Выученных карточек"),
                ),
                (
                    "total_sessions",
                    models.IntegerField(default=0, verbose_name="Всего сессий"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="Правильных ответов"),
                ),
                (
                    "last_study",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее изучение"
                    ),
                ),
                (
                    "streak_days",
                    models.IntegerField(default=0, verbose_name="Дней подряд"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика пользователя",
                "verbose_name_plural": "Статистика пользователей",
            },
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("correct", "Правильно"),
                            ("incorrect", "Неправильно"),
                            ("easy", "Легко"),
                            ("hard", "Сложно"),
                        ],
                        max_length=20,
                        verbose_name="Результат",
                    ),
                ),
                (
                    "response_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Время ответа (сек)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата сессии"),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="cards.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия изучения",
                "verbose_name_plural": "Сессии изучения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "next_review",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Следующее повторение",
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(default=1, verbose_name="Интервал (дни)"),
                ),
                (
                    "repetitions",
                    models.IntegerField(
                        default=0, verbose_name="Количество повторений"
                    ),
                ),
                (
                    "ease_factor",
                    models.FloatField(default=2.5, verbose_name="Коэффициент легкости"),
                ),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание",
                "verbose_name_plural": "Расписания",
            },
        ),
    ]
