# Generated by Django 4.2.7 on 2025-08-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_learned",
            field=models.BooleanField(default=False, verbose_name="Выучено"),
        ),
        migrations.AddField(
            model_name="card",
            name="times_correct",
            field=models.IntegerField(default=0, verbose_name="Правильных ответов"),
        ),
        migrations.AddField(
            model_name="card",
            name="times_studied",
            field=models.IntegerField(default=0, verbose_name="Количество изучений"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="last_reviewed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последнее изучение"
            ),
        ),
        migrations.AddField(
            model_name="studysession",
            name="quality_score",
            field=models.IntegerField(default=3, verbose_name="Оценка качества (0-5)"),
        ),
        migrations.AddField(
            model_name="studysession",
            name="user_answer",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Ответ пользователя"
            ),
        ),
        migrations.AddField(
            model_name="userstats",
            name="current_week_studied",
            field=models.IntegerField(default=0, verbose_name="Изучено на этой неделе"),
        ),
        migrations.AddField(
            model_name="userstats",
            name="study_time_minutes",
            field=models.IntegerField(default=0, verbose_name="Время изучения (мин)"),
        ),
        migrations.AddField(
            model_name="userstats",
            name="weekly_goal",
            field=models.IntegerField(
                default=50, verbose_name="Недельная цель (карточек)"
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="result",
            field=models.CharField(
                choices=[
                    ("perfect", "Идеально"),
                    ("correct", "Правильно"),
                    ("hard", "Сложно"),
                    ("incorrect", "Неправильно"),
                    ("failed", "Провал"),
                ],
                max_length=20,
                verbose_name="Результат",
            ),
        ),
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(upload_to="audio/", verbose_name="Аудио файл"),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=10, verbose_name="Язык"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудио файл",
                "verbose_name_plural": "Аудио файлы",
            },
        ),
    ]
